apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Values.component}}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::767398040211:role/prod-eks-ssm-ro
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-delete
    helm.sh/hook-weight: "-10"
  labels:
    app.kubernetes.io/name: {{.Values.component}}