apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Values.component}}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::767398040211:role/roboshop-init-cont-role-for-sa
  labels:
    app.kubernetes.io/name: {{.Values.component}}